### ISSUE TITLE
Sriov Exporter pod remains in CrashLoopBackOff if there is no sriov interface

### ISSUE THREAD

**Issue by ArunprakashD** [k8snetworkplumbingwg/sriov-network-metrics-exporter#14]
We are bringing up the sriov exporter in all the worker nodes as daemonset and some of the sriov exporter pod goes to crashloopbackoff as there is no sriov physical interface present in those nodes.

> sriov-metrics-exporter-2s4d7                              0/1     CrashLoopBackOff   2 (19s ago)   37s
> sriov-metrics-exporter-55bqd                              0/1     CrashLoopBackOff   2 (15s ago)   37s
> 
> user@cp-ovb-stack-1:~> kubectl logs -n monitoring sriov-metrics-exporter-2s4d7
> 2022/08/09 09:26:57 The kubepoddevice collector is enabled
> 2022/08/09 09:26:57 The vfstats collector is enabled
> 2022/08/09 09:26:57 no sriov net devices found on host

Is there a way to run the pods on the nodes without sriov interface and not going into CrashLoopBackOff, like keep running in a sleep mode? 

From the code logic, an error is thrown if there are no interface:

> if len(sriovPFs) == 0 {
		return sriovPFs, errors.New("no sriov net devices found on host")
	}

Daemonset file:

> apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: sriov-metrics-exporter
    app.kubernetes.io/version: v0.0.1
  name: sriov-metrics-exporter
  namespace: monitoring
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: sriov-metrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sriov-metrics-exporter
        app.kubernetes.io/version: v0.0.1
    spec:
      containers:
      - args:
        - --path.kubecgroup=/host/kubecgroup
        - --path.sysbuspci=/host/sys/bus/pci/devices/
        - --path.sysclassnet=/host/sys/class/net
        - --path.cpucheckpoint=/host/cpu_manager_state
        - --path.kubeletSocket=/host/kubelet.sock
        - --collector.kubepoddevice=true
        image: armdocker.general.se/proj_kds/3pp/sriov-network-metrics-exporter:v0.1-1
        imagePullPolicy: Always 
        name: sriov-metrics-exporter
        ports:
          - name: metrics
            containerPort: 9808
            hostPort: 9808
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        securityContext:
          capabilities:
            drop:
              - ALL      
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /host/kubelet.sock
          name: kubeletsocket
        - mountPath: /host/sys/bus/pci/devices
          name: sysbuspcidevices
          readOnly: true
        - mountPath: /host/sys/devices
          name: sysdevices
          readOnly: true
        - mountPath: /host/sys/class/net
          name: sysclassnet
          readOnly: true
        - mountPath: /host/kubecgroup
          name: kubecgroup
          readOnly: true
        - mountPath: /host/cpu_manager_state
          name: cpucheckpoint
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pod-resources/kubelet.sock
          type: "Socket"
        name: kubeletsocket
      - hostPath:
          path: /sys/fs/cgroup/cpuset/kubepods.slice/
          type: "Directory"
        name: kubecgroup
      - hostPath:
          path: /var/lib/kubelet/cpu_manager_state
          type: "File"
        name: cpucheckpoint
      - hostPath:
          path: /sys/class/net
          type: "Directory"
        name: sysclassnet
      - hostPath:
          path: /sys/bus/pci/devices
          type: "Directory"
        name: sysbuspcidevices
      - hostPath:
          path: /sys/devices
          type: "Directory"
        name: sysdevices
---

> apiVersion: v1
> kind: Service
> metadata:
>   name: sriov-metrics-exporter
>   namespace: monitoring
>   annotations:
>     prometheus.io/target: "true"
> spec:
>   selector:
>     app.kubernetes.io/name: sriov-metrics-exporter
>   ports:
>     - protocol: TCP
>       port: 9808
>       targetPort: 9808

**Comment by eoghanlawless** [comment]
The current implementation of SR-IOV Network Metrics Exporter doesn't support this as the sriovdev collector initializes with the available physical functions on deployment, and never updates again.

`//SriovdevCollector is initialized with the physical functions on the host. This is not updated after initialization.`

We could stop that error from occurring, but the metrics exporter will never see sriov device metrics.

This could be a feature request to enable some sort of trigger to re-scan for physical functions and remain idle if none found.
