### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by girisubhra** [k8snetworkplumbingwg/sriov-network-metrics-exporter#15]
I am getting this compilation error. Please suggest how it can be resolved
golangci-lint run
make: *** [Makefile:9: build] Killed
Error: error building at STEP "RUN make clean && make build": error while running runtime: exit status 2

**Comment by Eoghan1232** [comment]
Hi @girisubhra, seemed to be an issue with the golangci-lint version.
I have created a PR #16 to fix this. 
For now, you can update the version in the Makefile, until the PR is merged.

**Comment by girisubhra** [comment]
> Hi @girisubhra, seemed to be an issue with the golangci-lint version. I have created a PR #16 to fix this. For now, you can update the version in the Makefile, until the PR is merged.

Thank you very much it is built now. I have another doubt is this mandatory "docker push localhost:5000/sriov-metrics-exporter"

**Comment by Eoghan1232** [comment]
Hi @girisubhra, typically you would build an image, and push it to a local registry for your pod to pull the image down.

If you are testing locally, you do not need to push to a registry.
If you are testing on a multi-node cluster, I'd recommend setting up a registry.
