### ISSUE TITLE
Missing configmap "sriov-network-metrics-exporter" manifest

### ISSUE THREAD

**Issue by balaramvedulla** [k8snetworkplumbingwg/sriov-network-metrics-exporter#38]
Hi,

When the DaemonSet is applied, it has been looking for a Configmap named "sriov-network-metrics-exporter", but there is no such configmap definition in the `sriov-network-metrics-exporter/deployment/daemonset.yaml`

Could someone provide what is expected in this Configmap ? Thanks !

**Comment by zeeke** [comment]
Hi @balaramvedulla , that configmap has been remove by 
- https://github.com/k8snetworkplumbingwg/sriov-network-metrics-exporter/pull/37

There must be a leftover reference to that. Taking a look
